### ISSUE TITLE
我想手动部署zmirror，但是apache启动不了。

### ISSUE THREAD

**Issue by ClarkeCheng** [aploium/zmirror#13]
作者你好，我按照《部署支持HTTPS和HTTP2.0的镜像》一步一步安装一个google镜像，但是用的是自己签发的证书。
这个证书有两个文件，一个key文件，一个crt文件。我把配置文件全部弄好了，执行sudo service apache2 restart却显示如下：
root@UnawareOnly-VM:~# sudo service apache2 restart
 * Restarting Apache httpd web server apache2                                           Action 'start' failed.
The Apache error log may have more information.

我就看了看错误日志，日志如下：
[Fri Sep 30 08:40:06.965851 2016] [ssl:emerg] [pid 6880:tid 3074701952] AH02561: Failed to configure certificate g.yandere.cf:443:0, check /root/zmirror/1.key
[Fri Sep 30 08:40:06.965935 2016] [ssl:emerg] [pid 6880:tid 3074701952] SSL Library Error: error:0906D06C:PEM routines:PEM_read_bio:no start line (Expecting: CERTIFICATE) -- Bad file contents or format - or even just a forgotten SSLCertificateKeyFile?
[Fri Sep 30 08:40:06.965957 2016] [ssl:emerg] [pid 6880:tid 3074701952] SSL Library Error: error:140AD009:SSL routines:SSL_CTX_use_certificate_file:PEM lib
[Fri Sep 30 08:44:31.538445 2016] [ssl:emerg] [pid 6923:tid 3074718336] AH02561: Failed to configure certificate g.yandere.cf:443:0, check /root/zmirror/1.key
[Fri Sep 30 08:44:31.538644 2016] [ssl:emerg] [pid 6923:tid 3074718336] SSL Library Error: error:0906D06C:PEM routines:PEM_read_bio:no start line (Expecting: CERTIFICATE) -- Bad file contents or format - or even just a forgotten SSLCertificateKeyFile?
[Fri Sep 30 08:44:31.538665 2016] [ssl:emerg] [pid 6923:tid 3074718336] SSL Library Error: error:140AD009:SSL routines:SSL_CTX_use_certificate_file:PEM lib
[Fri Sep 30 08:46:59.981155 2016] [ssl:emerg] [pid 6954:tid 3074042496] AH02561: Failed to configure certificate g.yandere.cf:443:0, check /root/zmirror/1.key
[Fri Sep 30 08:46:59.981240 2016] [ssl:emerg] [pid 6954:tid 3074042496] SSL Library Error: error:0906D06C:PEM routines:PEM_read_bio:no start line (Expecting: CERTIFICATE) -- Bad file contents or format - or even just a forgotten SSLCertificateKeyFile?
[Fri Sep 30 08:46:59.981261 2016] [ssl:emerg] [pid 6954:tid 3074042496] SSL Library Error: error:140AD009:SSL routines:SSL_CTX_use_certificate_file:PEM lib

我百度了一下都没有找到解决方法，还有我用zmirror-onekey用同样的证书却可以安装完毕，这是怎么回事？

**Comment by aploium** [comment]
Apache没有访问 /root/ 的权限
把证书放在其他目录试试看

**Comment by ClarkeCheng** [comment]
谢谢解答，但是我那个用来装zmirror的VPS的SSH今天连不上了，ping IP也超时，只好换一台了。
