### ISSUE TITLE
请问安装apache时这个命令找不到是怎么回事？

### ISSUE THREAD

**Issue by ClarkeCheng** [aploium/zmirror#14]
作者你好，我在一台新的VPS上装新版apache，可是不知道它的系统是怎么回事，安装的时候没有想象中的那么顺利。
sudo a2enmod rewrite mime include headers filter expires deflate autoindex setenvif ssl http2
sudo: a2enmod: command not found
root@ubuntu:~# 

系统是Ubuntu-14.04.1-LTS-64bit。

**Comment by aploium** [comment]
可能是教程里的一个问题
请执行一下
`sudo apt-get install apache2 -y`

**Comment by ClarkeCheng** [comment]
OK，谢谢，已经可以安装apache了。
