### ISSUE TITLE
请问执行sudo service apache2 restart不成功是怎么回事？

### ISSUE THREAD

**Issue by ClarkeCheng** [aploium/zmirror#15]
root@ubuntu:~# sudo service apache2 restart
 * Restarting Apache httpd web server apache2                                    [fail] 
 * The apache2 configtest failed.
Output of config test was:
AH00526: Syntax error on line 19 of /etc/apache2/conf-enabled/google.conf:
Invalid command 'WSGIDaemonProcess', perhaps misspelled or defined by a module not included in the server configuration
Action 'configtest' failed.
The Apache error log may have more information.
root@ubuntu:~# 

第19行是
`WSGIDaemonProcess zmirror_google user=www-data group=www-data threads=16`
我没有改过这个，我只是改了路径（在/var/www/文件夹里）和域名还有证书路径（在/etc/apache/文件夹里）。

**Comment by aploium** [comment]
原因是wsgi没有安装

需要把教程里`apt-get install apache2 -y`之后的几句话也执行掉
```shell
sudo a2enmod rewrite mime include headers filter expires deflate autoindex setenvif ssl http2
sudo apt-get install libapache2-mod-wsgi-py3 -y
```

**Comment by ClarkeCheng** [comment]
我记得我执行了，但是还是会这样。
`root@ubuntu:~# sudo a2enmod rewrite mime include headers filter expires deflate autoindex setenvif ssl http2
Module rewrite already enabled
Module mime already enabled
Considering dependency mime for include:
Module mime already enabled
Module include already enabled
Module headers already enabled
Module filter already enabled
Module expires already enabled
Considering dependency filter for deflate:
Module filter already enabled
Module deflate already enabled
Module autoindex already enabled
Module setenvif already enabled
Considering dependency setenvif for ssl:
Module setenvif already enabled
Considering dependency mime for ssl:
Module mime already enabled
Considering dependency socache_shmcb for ssl:
Module socache_shmcb already enabled
Module ssl already enabled
Module http2 already enabled
root@ubuntu:~# sudo apt-get install libapache2-mod-wsgi-py3 -y
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libapache2-mod-wsgi-py3 is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@ubuntu:~# sudo service apache2 restart
 * Restarting Apache httpd web server apache2                                    [fail] 
 * The apache2 configtest failed.
Output of config test was:
AH00526: Syntax error on line 19 of /etc/apache2/conf-enabled/google.conf:
Invalid command 'WSGIDaemonProcess', perhaps misspelled or defined by a module not included in the server configuration
Action 'configtest' failed.
The Apache error log may have more information.
root@ubuntu:~# 
`

**Comment by aploium** [comment]
再执行 `a2enmod wsgi` 呢

**Comment by ClarkeCheng** [comment]
好像还是不行。
root@ubuntu:~# a2enmod wsgi
Enabling module wsgi.
To activate the new configuration, you need to run:
  service apache2 restart
root@ubuntu:~# sudo service apache2 restart
 * Restarting Apache httpd web server apache2                                           AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
Action 'start' failed.
The Apache error log may have more information.
                                                                                 [fail]

**Comment by aploium** [comment]
apache error log里是怎么写的
在 `/var/log/apache2/` 里

**Comment by ClarkeCheng** [comment]
/var/log/apache2/error.log里面是这么写的：
AH00016: Configuration Failed
AH00016: Configuration Failed
AH00016: Configuration Failed
AH00016: Configuration Failed

**Comment by aploium** [comment]
另一个error文件, google镜像的

**Comment by aploium** [comment]
在 `/etc/apache2/apache2.conf` 中设置一下`ServerName`试试看
比如
`ServerName loli.com`

**Comment by ClarkeCheng** [comment]
我在/etc/apache2/apache2.conf的开头加入
`ServerName localhost:80`
问题解决了，可是执行
`sudo service apache2 restart`
还是有错。

root@ubuntu:~# sudo service apache2 restart
 * Restarting Apache httpd web server apache2                                           Action 'start' failed.
The Apache error log may have more information.
                                                                                 [fail]
root@ubuntu:~# 

我就看了看/var/log/apache2/zmirror-google_ssl_error.log
发现好像是证书的问题，这次我没有放在root文件夹里。
[Sat Oct 01 12:52:10.759831 2016] [ssl:emerg] [pid 2267:tid 139696432801664] AH02561: Failed to configure certificate g.yandere.cf:443:0, check /etc/apache2/1.key
[Sat Oct 01 12:52:10.759991 2016] [ssl:emerg] [pid 2267:tid 139696432801664] SSL Library Error: error:0906D06C:PEM routines:PEM_read_bio:no start line (Expecting: CERTIFICATE) -- Bad file contents or format - or even just a forgotten SSLCertificateKeyFile?
[Sat Oct 01 12:52:10.760014 2016] [ssl:emerg] [pid 2267:tid 139696432801664] SSL Library Error: error:140AD009:SSL routines:SSL_CTX_use_certificate_file:PEM lib

是不是它只能要pem格式的证书？

**Comment by aploium** [comment]
有可能, 这个我也不知道..

**Comment by ClarkeCheng** [comment]
好吧，我决定用let's encrypt，并且成功了，不过怎么设置它自动更新证书呢？

**Comment by aploium** [comment]
.....自行google...........
