### ISSUE TITLE
发现Youtube PC版镜像的一个问题：看一个视频常常是视频加载出来了，但是上传者的头像、旁边的“接下来播放”里视频的图片和下面的评论却迟迟加载不出来

### ISSUE THREAD

**Issue by ClarkeCheng** [aploium/zmirror#17]
这样导致看视频不能刚打开就可以切换到剧场模式，原版Youtube是没有问题的。

**Comment by ClarkeCheng** [comment]
示例地址：https://ytb-pc.zmirrordemo.com/watch?v=77uEIcjZ-rU

**Comment by aploium** [comment]
## 原因
这是一个很早以前就已经发现的bug, 原因是youtube会请求一个 /qoe 页面, 但是会导致循环307
浏览器不得不等到307次数过多, 强制终止请求后才能继续加载下面的图片和评论

## 修复方案
目前没有能想到的修复方案QAQ, 导致循环307的根源原因也未知

后面的版本(大概是v0.31)会加入对重定向循环的检测, 尽早终止掉这样的无限循环, 但是治标不治本
其实不止是youtube, 其他一些镜像里也会出现循环307的问题

想要真正修复....大概只能等以后加入更加智能的重写和请求猜测逻辑了,
