### ISSUE TITLE
请问下我一键部署后其他网站都可以访问，唯独google镜像无法访问，是什么原因呢？

### ISSUE THREAD

**Issue by wuyan1222** [aploium/zmirror#21]
一键部署脚本部署了所有镜像，其他的都可以访问，谷歌的镜像却不行，是因为我是四级域名？
https://google.wuyan.org.cn

**Comment by aploium** [comment]
![sc 2016-10-11_22-00-42](https://cloud.githubusercontent.com/assets/15957250/19273279/7e561626-8ffe-11e6-8691-16abfd9846dc.png)

**Comment by wuyan1222** [comment]
使用ie浏览器可以打开，看来是浏览器缓存的问题。谢谢。
