### ISSUE TITLE
群主！youtube镜像打不开视频了？？

### ISSUE THREAD

**Issue by yy0535** [aploium/zmirror#28]
群主！youtube镜像打不开视频了？？

>提示：

ytb-pc.zmirrordemo.com 网页无法正常运作

ytb-pc.zmirrordemo.com 将您重定向的次数过多。

**Comment by aploium** [comment]
未能复现问题.... 请清除缓存再尝试

qwq 等v0.31以后加入重定向死循环检测以后会缓解

**Comment by yy0535** [comment]
谢谢你，哥们，你真是个牛人
