### ISSUE TITLE
局域网内部可以部署一件脚本吗？

### ISSUE THREAD

**Issue by ffspace810** [aploium/zmirror#30]
不绑定域名用ip地址的方式可以吗？

**Comment by aploium** [comment]
不可以的.
那样就不能用https了, https必须是域名

zmirror本身对IP是友好的(不过我也不能保证100%支持)

如果只是自己人用的话, 甚至不需要用Apache/Nginx, 用flask自带服务器就行

1. 将对应的配置文件复制到zmirror根目录, [见此](https://github.com/aploium/zmirror/tree/master/more_configs#使用方法)
2. 在`config.py`中设置`my_host_name`为本机IP
3. 在`config.py`最后面加入这两行, 来使zmirror接受本机以外的请求
```python
built_in_server_host = '0.0.0.0'
built_in_server_debug = False
```
4. 执行`python3 wsgi.py` 来运行zmirror

**Comment by ffspace810** [comment]
多谢指点。如果我把内网服务器映射到外网（外网固定ip），但端口不是443，这样可以吗？

**Comment by aploium** [comment]
可以的.
那样的话`my_host_name`就需要设置成外网出口的那个IP
还需要加一行
`my_host_port = 外网出口的实际端口`

虽然zmirror支持非标准端口, 但是可能会有潜在的bug

**Comment by ffspace810** [comment]
好的，再次感谢。
