### ISSUE TITLE
我的按照手动出现如下提示

### ISSUE THREAD

**Issue by ianzhou233** [aploium/zmirror#31]
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 2604:a880:1:20::e1e:d001（我的vps的）IPV6地址. Set the 'ServerName' directive globally to suppress this message。是因为vps有IPV6地址的原因还是自己的域名解析的问题？

**Comment by aploium** [comment]
这个没有影响的, 可以放心无视掉它

**Comment by ianzhou233** [comment]
谢谢，不知道最近有没有更新

2016-10-21 21:30 GMT+08:00 Aploium <notifications@github.com>:
