### ISSUE TITLE
为什么要三级域名呢？

### ISSUE THREAD

**Issue by emesonz** [aploium/zmirror#33]
为什么要是三级域名呢？
一级或者二级不行吗？
直接xxx.com
或者www.xxx.com不行？

**Comment by aploium** [comment]
三级域名就是指`www.xxx.com`这种
三级域名只是**建议**,因为**可能**被镜像网站中会有某些正则或者字符串分隔逻辑会对域名级数敏感
不过从目前的测试来看, 各个镜像对二级到四级域名都没用出现兼容性问题

如果有需要的话可以放心使用二级到四级域名
