### ISSUE TITLE
出现错误提示

### ISSUE THREAD

**Issue by emesonz** [aploium/zmirror#34]
Detail: Failed to connect to 104.28.18.72:443 for TLS-SNI-01
   challenge

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A record(s) for that domain
   contain(s) the right IP address. Additionally, please check that
   you have an up-to-date TLS configuration that allows the server to
   communicate with the Certbot client.
 - Your account credentials have been saved in your Certbot
   configuration directory at /etc/letsencrypt. You should make a
   secure backup of this folder now. This configuration directory will
   also contain certificates and private keys obtained by Certbot so
   making regular backups of this folder is ideal.

a记录没有问题。。已经尝试了两个域名了。

**Comment by aploium** [comment]
这不是zmirror的问题，请尝试手动运行，readme中有说明。
