### ISSUE TITLE
一键包错误提示

### ISSUE THREAD

**Issue by emesonz** [aploium/zmirror#35]
* Restarting Apache httpd web server apache2                                                                                                                                                                    AH00557: apache2: apr_sockaddr_info_get() failed for localhost.localdomain
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.0.1. Set the 'ServerName' directive globally to suppress this message
安装一键包的时候出现的提示，应该怎么解决？

**Comment by aploium** [comment]
安装脚本的issues请发到 https://github.com/aploium/zmirror-onekey/issues

**Comment by aploium** [comment]
这个没有影响的, 可以放心无视
