### ISSUE TITLE
如何替换目标站的一些代码呢

### ISSUE THREAD

**Issue by emesonz** [aploium/zmirror#37]
目标站的logo啊，广告啊，标题啊，之类的
可以替换吗

**Comment by aploium** [comment]
可以, 具体请看`custom_func.sample.py`里的说明, 你需要自己写相关的替换代码

**Comment by emesonz** [comment]
Please remember to set `custom_text_rewriter_enable` to True in the config
是在config.py 里加上custom_text_rewriter_enable=true 这一段代码开启吗？
然后在custom_func.sample.py 里添加替换代码，比如：raw_text = raw_text.replace('xxx', 'yyy')
吗？
我尝试了这样，似乎网站都打不开了。。。

**Comment by aploium** [comment]
需要把`custom_func.sample.py`重命名为`custom_func.py`

麻烦仔细阅读说明.......
请阅读`custom_text_rewriter_enable`在config_default.py里的说明

**Comment by emesonz** [comment]
如何替换多个代码呢？
比如111替换为222
333替换为444

**Comment by aploium** [comment]
你需要自己写对应的替换代码(python)......
custom_text_rewriter相当于提供给你一个自己操作对方服务器响应内容的接口, 函数会把对方给你的东西(html/js/css)传进这个函数, 你在这个函数里对它进行修改(具体怎么改是你的事)
然后再放回给zmirror, 继续zmirror自身的重写逻辑
