### ISSUE TITLE
有关正则替换的一些问题

### ISSUE THREAD

**Issue by liaolushen** [aploium/zmirror#4]
你好，我正在看你的代码，对网址替换有个感兴趣的地方
```py
# 前缀, 必须有  'action='(表单) 'href='(链接) 'src=' 'url('(css) '@import'(css) '":'(js/json, "key":"value")
```
这里看到你对js的中的网址替换，就只有一种情况的替换，实际的操作中，会不会有更复杂的情况的呢？

**Comment by aploium** [comment]
可能有...但是我还没遇到过(或者已经遇到过, 但是没有发现)
一部分正则没有匹配到的url会在后面的纯文本替换中被替换掉, 就是这个 response_text_rewrite()
其实 response_text_rewrite() 这个东西, 我接下来也想把它用正则改写掉, 但是最近没空orz

**Comment by liaolushen** [comment]
不知道你有没有考虑过一个网址反代多个网站的可行性（不用二级域名），最近一直在想，感觉都没有很好的办法。

**Comment by aploium** [comment]
这个在程序里已经有实现的，Google和维基就是一个域名放两个镜像。
现有的机制是根据referer来区分属于哪个站，
这种机制对wiki这样相当简单的站效果是很好的
但是对于更加复杂的巨型网站就没办法了
比如说tiwtter手机和pc，就只能分成两个域名

**Comment by liaolushen** [comment]
我现在想使用一个"127.0.0.1?u=目标网址"的形式做一个全站的反向代理，在实现时我就需要对所有的绝对地址和相对地址进行替换，但是我发现查找js中的相对地址过于困难。然后我就想js中的相对地址不进行更改，等它发送请求到我后台，我再根据referer进行判断转发，但在处理Twitter的时候最后效果感觉不太好，不确定是方法问题还是实现问题，能不能给点意见呢，最近因为这个也是非常苦恼

**Comment by aploium** [comment]
是方法问题... referer对复杂的站在理论上就是不行的....像twitter这种referer太乱了根本没法用
