### ISSUE TITLE
YouTube有流量走但是没有视频出现

### ISSUE THREAD

**Issue by FYpanda** [aploium/zmirror#40]
刚安装了发现油管只有流量在走，没有视频出现，请问是怎么回事？![d8 c11z vo f0runwl_o m](https://cloud.githubusercontent.com/assets/20028752/20309228/277448c4-ab82-11e6-8ff9-fd54215b7eb6.png)

**Comment by aploium** [comment]
请问能不能给个地址？

**Comment by FYpanda** [comment]
https://y.fxwj.pub/，密码就是问题，其他貌似没问题，就是有流量没视频！

**Comment by FYpanda** [comment]
https://y.fxwj.pub/
密码就是问题，其他貌似没问题，就是有流量没视频！

**Comment by FYpanda** [comment]
请问知道是什么问题没视频了吗，我vultr没多少余额了，网站撑不了多久了！

**Comment by aploium** [comment]
与requests 2.12 的兼容性问题, (requests是zmirror依赖的一个核心库)
requests 2.12设置了非常严格的url格式规范, 对不规范的url会直接拒绝发起请求

而youtube视频的url很不巧长得像这样:
https://a--b--f3456.googlevideo.com/blahblah
域名中包含横线(-), 不符合requests 2.12 的规范, 会拒绝发出请求, zmirror就无法工作了.

目前没有很好的解决办法, 临时的办法是将requests版本限制为 2.11及以下

如果是用一键脚本部署的, 请重新部署一次, 加入了对requests的版本限制
#40 #41 #44

**Comment by notlosing** [comment]
今天剛裝了Zmirror最新版本在Google Cloud上， youtube也是只有流量沒法播放視頻。加了個BBC中文網的鏡像，也是沒法播放視頻。
