### ISSUE TITLE
youtube无法播放视频

### ISSUE THREAD

**Issue by sunnoy** [aploium/zmirror#41]
浏览器chrome  54.0.2840.99 m (64-bit) 系统windows10 专业版 64位  服务端centos6

**Comment by sunnoy** [comment]
站点 y.lxdd.ml

**Comment by aploium** [comment]
与requests 2.12 的兼容性问题, (requests是zmirror依赖的一个核心库)
requests 2.12设置了非常严格的url格式规范, 对不规范的url会直接拒绝发起请求

而youtube视频的url很不巧长得像这样:
https://a--b--f3456.googlevideo.com/blahblah
域名中包含横线(-), 不符合requests 2.12 的规范, 会拒绝发出请求, zmirror就无法工作了.

目前没有很好的解决办法, 临时的办法是将requests版本限制为 2.11及以下

如果是用一键脚本部署的, 请重新部署一次, 加入了对requests的版本限制
#40 #41 #44

**Comment by seramat** [comment]
请问，使用@yumin9822一键部署的，怎么限制request 2.11版本？
