### ISSUE TITLE
youtube加载了，却没有播放？

### ISSUE THREAD

**Issue by ttestdock** [aploium/zmirror#44]
https://y2b-goproxy2.rhcloud.com
openshift平台，python 3.3
windows10 edge & IE 可以看到进度条预览，点击进度条也可以出现图片，就是不能播放？

**Comment by aploium** [comment]
与requests 2.12 的兼容性问题, (requests是zmirror依赖的一个核心库)
requests 2.12设置了非常严格的url格式规范, 对不规范的url会直接拒绝发起请求

而youtube视频的url很不巧长得像这样:
https://a--b--f3456.googlevideo.com/blahblah
域名中包含横线(-), 不符合requests 2.12 的规范, 会拒绝发出请求, zmirror就无法工作了.

目前没有很好的解决办法, 临时的办法是将requests版本限制为 2.11及以下

如果是用一键脚本部署的, 请重新部署一次, 加入了对requests的版本限制
#40 #41 #44
