### ISSUE TITLE
一键安装的，几个模板都安装了，现在想安装别的模板

### ISSUE THREAD

**Issue by emesonz** [aploium/zmirror#47]
一键安装的系统里面的6个模板都安装了已经
现在想自己安装几个别的模板
该怎么操作呢？

**Comment by ClarkeCheng** [comment]
手工部署呗，我都是手工一个个部署的，虽然很麻烦，但是我能了解它是如何运行的。

**Comment by aploium** [comment]
请在脚本中安装那个通用模板, 然后将自己想要的模板(在more_configs里)文件复制并替换 config.py
.....太忙了,....没时间把剩下的加入....
