### ISSUE TITLE
请问在openshift和heroku上可以用吗

### ISSUE THREAD

**Issue by zxq2233** [aploium/zmirror#5]
请问在openshift和heroku上可以用吗

**Comment by aploium** [comment]
并没有测试过....但是理论上只要是能跑Python3的地方都可以 欢迎测试
可以加我QQ 358890739

**Comment by yaoyichi2011** [comment]
openshift可以，不过直接用模板会有少量页面出现乱码

**Comment by aploium** [comment]
我主要是在Ramnode(LA)测试的

-------- 原始邮件 --------
发件人： yaoyichi2011 <notifications@github.com> 
日期: 2016-07-25  12:07  (GMT+08:00) 
收件人： aploium/zmirror <zmirror@noreply.github.com> 
抄送： Aploium <i@z.codes>, Comment <comment@noreply.github.com> 
主题： Re: [aploium/zmirror] 请问在openshift和heroku上可以用吗 (#5) 

openshift可以，不过直接用模板会有少量页面出现乱码
