### ISSUE TITLE
应该是 tumblr 而不是 thumblr。。。

### ISSUE THREAD

**Issue by zhangmikoto** [aploium/zmirror#56]
嗯，就这个拼写问题，其他的都很好，感谢作者！

**Comment by zhangmikoto** [comment]
另外，google设置不了其他语言。。。可以在配置文件修改以达到此目的嘛？就像https://github.com/cuber/ngx_http_google_filter_module/blob/master/README.zh-CN.md
这里面的语言修改一样。

**Comment by zjuchenyuan** [comment]
fixed
