### ISSUE TITLE
请问如何用上证书？

### ISSUE THREAD

**Issue by ClarkeCheng** [aploium/zmirror#6]
请问如何用上证书？

**Comment by aploium** [comment]
zmirror本身不负责ssl加密，需要使用Apache来加密即Apache使用wsgi来调用zmirror如果不理解的话，可以类比成Apache调用PHP，PHP本身不负责ssl，由Apache负责ssl
至于Apache本身如何开启https，请Google一下
具体步骤可以看readme最后面，Deploy To Server 部分
ssl证书本身需要进行申请现在免费的证书有 wosign startssl 和 let's encryptlet's encrypt对新手比较友好，document非常详细。

**Comment by aploium** [comment]
我去。。为什么用邮件回复会丢失所有换号。。
QAQ

**Comment by ClarkeCheng** [comment]
不会用Apache调用zmirror呢，能不能用中文说一下方法。英文我真的是看不懂。

**Comment by aploium** [comment]
请看这个文档
http://flask.pocoo.org/docs/0.11/deploying/mod_wsgi/

至于...中文.....臣妾也做不到啊.....这些配置本身就全是英文的
同学..多查查字典吧, 没几个单词的



google demo 站的配置文件是这样的(https)
其中 /var/www/google 是zmirror的程序文件夹

```
# Ubuntu16.04-x86_64 with Apache2.4
# /etc/apache2/sites-enabled/google.conf
<IfModule mod_ssl.c>
    SSLCipherSuite HIGH:MEDIUM:!aNULL:!MD5  # 这个也没什么用, 无视掉就行
    <VirtualHost *:443>
        ServerName g.zmirrordemo.com  # 域名

        ServerAdmin root@localhost  # 这个没用的

        ErrorLog ${APACHE_LOG_DIR}/google_ssl_error.log
        CustomLog ${APACHE_LOG_DIR}/google_ssl_access.log combined

        # ##### WSGI 这部分是重点  ######
        WSGIDaemonProcess zmirror_google user=www-data group=www-data threads=16
        WSGIScriptAlias / /var/www/google/wsgi.py
        WSGIPassAuthorization On

        # 给予zmirror文件夹权限
        <Directory /var/www/google>
            WSGIProcessGroup zmirror_google
            WSGIApplicationGroup %{GLOBAL}
            Order deny,allow
            Allow from all
        </Directory>
        

        SSLEngine on
        SSLCertificateFile  /etc/ssl/certs/google-ssl-cert.crt  # 私钥
        SSLCertificateKeyFile /etc/ssl/private/google-ssl-private-key.key  # 证书
        SSLCertificateChainFile /etc/ssl/certs/wosign_root_bundle.crt  # 证书链(申请证书的时候对方会给你的)

    </VirtualHost>
</IfModule>
```

**Comment by aploium** [comment]
对了, 因为zmirror用的是Python3, 安装wsgi的时候不能用它给的那个命令

**Comment by aploium** [comment]
请看这篇文档 [部署支持HTTPS和HTTP/2的zmirror镜像](https://github.com/aploium/zmirror/wiki/%E9%83%A8%E7%BD%B2%E6%94%AF%E6%8C%81HTTPS%E5%92%8CHTTP2.0%E7%9A%84%E9%95%9C%E5%83%8F)

**Comment by ClarkeCheng** [comment]
好的，我想问的是centos系统用得了吗？

**Comment by aploium** [comment]
可以用, 但是需要你自己折腾了.
那个教程只适用于Ubuntu

**Comment by aploium** [comment]
部署教程在多家VPS上测试通过. 
CentOS/win/mac下暂时没有写部署教程的计划
如果centos部署有困难的, 请重装为Ubuntu(建议16.04-x86_64)后参考部署教程部署
