### ISSUE TITLE
分享可以流畅观看YouTUbe视频的浏览器

### ISSUE THREAD

**Issue by loveybaby** [aploium/zmirror#64]
![11](https://cloud.githubusercontent.com/assets/22636272/24577572/b2df8aa4-1702-11e7-8528-829ef1e99882.PNG)

**Comment by loveybaby** [comment]
![12](https://cloud.githubusercontent.com/assets/22636272/24577574/c9724e00-1702-11e7-9f3c-f0d1c1777169.PNG)

**Comment by loveybaby** [comment]
项目地址：https://github.com/Alvin9999/new-pac/wiki
首选**GoAgent版**或**GoProxy版**

**Comment by zjuchenyuan** [comment]
unrelated
