### ISSUE TITLE
YouTube视频无法播放

### ISSUE THREAD

**Issue by ACGunion** [aploium/zmirror#73]
发生于chrome61.0.3159.6/IE 11
服务端 Ubuntu 16.04
使用 https://github.com/aploium/zmirror-onekey  一键部署
视频资源链接提示重定向过多
![image](https://user-images.githubusercontent.com/14949366/28468918-18af0dc6-6e67-11e7-9d2e-e31382b708d2.png)

**Comment by zjuchenyuan** [comment]
代码很久没有更新了，原作者没有持续维护的计划。。。欢迎帮忙找bug提PR

**Comment by Sphaela** [comment]
config.py:
custom_text_rewriter_enable = False
url_custom_redirect_enable = False

**Comment by Sphaela** [comment]
config.py:
custom_text_rewriter_enable = False
url_custom_redirect_enable = False

不要登入Youtube 会坑…

**Comment by zby1234** [comment]
@zjuchenyuan 请问有解决办法了吗

**Comment by zjuchenyuan** [comment]
see #86
