### ISSUE TITLE
请问如何实现一台VPS运行多个镜像，并且端口一样但域名不同？

### ISSUE THREAD

**Issue by ClarkeCheng** [aploium/zmirror#8]
请问如何实现一台VPS运行多个镜像，并且端口一样但域名不同？

**Comment by ClarkeCheng** [comment]
不好意思，看错了，以前我记得要修改

**Comment by aploium** [comment]
`Running on http://127.0.0.1:80/ `
直接运行的话, 监听的是本地
就是说, 只接受本地的访问

如果想要直接运行, 接受外网的请求, 那么需要在config里加两句话:
> **以下是来自 wsgi.py 中的说明**
>如果你想直接用本程序给外网访问, 请在 config.py 末尾加两行配置
>!!警告!! 无论如何都不要修改 config_default.py, 否则程序将无法通过 git pull 来升级
>
>```python
>built_in_server_host='0.0.0.0'
>built_in_server_debug=False
>```
>ps:字母在行首, 行首不要有空格

  
当然, 最理想的还是按照教程来部署, 
直接运行wsgi只是为了测试程序能正常用. 
使用Apache部署的话, 性能和安全性都有好处, 而且可以支持HTTPS

WARING里也给你了提示 
[部署支持HTTPS和HTTP/2的镜像](https://github.com/aploium/zmirror/wiki/%E9%83%A8%E7%BD%B2%E6%94%AF%E6%8C%81HTTPS%E5%92%8CHTTP2.0%E7%9A%84%E9%95%9C%E5%83%8F)

**Comment by ClarkeCheng** [comment]
不好意思，我写错了。刚刚那个问题是我的失误，现在我知道怎么解决了。现在想问这个新的问题。

**Comment by aploium** [comment]
对了....你可以试试看zmirror的gitter, 可以即时聊天
点这个图标
[![Gitter](https://badges.gitter.im/zmirror/zmirror.svg)](https://gitter.im/zmirror/zmirror?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)  

新问题....新开一个issue吧

**Comment by aploium** [comment]
@ClarkeCheng 
教程已经完成:
[在一台VPS部署多个zmirror镜像](https://github.com/aploium/zmirror/wiki/%E5%9C%A8%E4%B8%80%E5%8F%B0VPS%E9%83%A8%E7%BD%B2%E5%A4%9A%E4%B8%AAzmirror%E9%95%9C%E5%83%8F)
