### ISSUE TITLE
qiniu好像没起作用

### ISSUE THREAD

**Issue by salamer** [aploium/zmirror#9]
我开了三个域名，然后是拿代instagram的域名给的qiniu
但是并没有转到qiniu，一切都按教程脚本来

**Comment by aploium** [comment]
非常感谢, 已经重现问题

**Comment by aploium** [comment]
BTW:这几天七牛回源的时候会出现534错误, 拉取不到资源, 我也不知道为什么
难道七牛开始封杀国外网站的回源?
暂时不建议使用七牛, 会导致很多资源加载不了

**Comment by aploium** [comment]
额...很抱歉...刚刚以为重现问题, 是我弄错了
在测试站点无法重现问题
![sc 2016-09-21_08-21-08](https://cloud.githubusercontent.com/assets/15957250/18693491/9befd896-7fd4-11e6-8319-d81d500b1ac0.jpg)
请再检查一下配置文件
